### ISSUE TITLE
Build: `pod install` 之后出现问题

### ISSUE THREAD

**Issue by peterzililuo** [songkuixi/Keeping#4]
我在Build的时候有问题：
当我运行`pod install`的时候，提示说：
`No 'Podfile' found in the project directory`

**Comment by songkuixi** [comment]
请进入到`Keeping`子目录里再运行这条

**Comment by peterzililuo** [comment]
好像没有办法下载`AVOSCloud`库诶：
`CocoaPods could not find compatible versions for pod "AVOSCloud":`

**Comment by songkuixi** [comment]
不是很了解这个情况 按照这个链接来看应该还是叫这个名字 你可能需要升级下本地pod库 https://leancloud.cn/docs/start.html
